# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alsui2.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlsWindow(object):
    def setupUi(self, AlsWindow):
        AlsWindow.setObjectName("AlsWindow")
        AlsWindow.resize(1038, 739)
        self.centralwidget = QtWidgets.QWidget(AlsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 1031, 148))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbPlay = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pbPlay.setObjectName("pbPlay")
        self.horizontalLayout.addWidget(self.pbPlay)
        self.pbPause = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pbPause.setEnabled(False)
        self.pbPause.setObjectName("pbPause")
        self.horizontalLayout.addWidget(self.pbPause)
        self.pbStop = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pbStop.setEnabled(False)
        self.pbStop.setObjectName("pbStop")
        self.horizontalLayout.addWidget(self.pbStop)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.cDark = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.cDark.setObjectName("cDark")
        self.gridLayout_3.addWidget(self.cDark, 2, 2, 1, 1)
        self.pbWork = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pbWork.setObjectName("pbWork")
        self.gridLayout_3.addWidget(self.pbWork, 3, 0, 1, 1)
        self.fScan = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.fScan.setObjectName("fScan")
        self.gridLayout_3.addWidget(self.fScan, 1, 1, 1, 1)
        self.pbScan = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pbScan.setObjectName("pbScan")
        self.gridLayout_3.addWidget(self.pbScan, 1, 0, 1, 1)
        self.fDark = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.fDark.setEnabled(False)
        self.fDark.setObjectName("fDark")
        self.gridLayout_3.addWidget(self.fDark, 2, 1, 1, 1)
        self.pbDark = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pbDark.setEnabled(False)
        self.pbDark.setObjectName("pbDark")
        self.gridLayout_3.addWidget(self.pbDark, 2, 0, 1, 1)
        self.fWork = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.fWork.setObjectName("fWork")
        self.gridLayout_3.addWidget(self.fWork, 3, 1, 1, 1)
        self.lCounter = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lCounter.setFont(font)
        self.lCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.lCounter.setObjectName("lCounter")
        self.gridLayout_3.addWidget(self.lCounter, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cAlign = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.cAlign.setObjectName("cAlign")
        self.gridLayout_2.addWidget(self.cAlign, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 4, 0, 1, 1)
        self.cEnablewww = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.cEnablewww.setObjectName("cEnablewww")
        self.gridLayout_2.addWidget(self.cEnablewww, 2, 0, 1, 1)
        self.cKeepframes = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.cKeepframes.setObjectName("cKeepframes")
        self.gridLayout_2.addWidget(self.cKeepframes, 1, 0, 1, 1)
        self.pbSave = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pbSave.setObjectName("pbSave")
        self.gridLayout_2.addWidget(self.pbSave, 5, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.tbLog = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tbLog.setFont(font)
        self.tbLog.setObjectName("tbLog")
        self.horizontalLayout_2.addWidget(self.tbLog)
        self.image_stack = QtWidgets.QLabel(self.centralwidget)
        self.image_stack.setGeometry(QtCore.QRect(0, 140, 1031, 451))
        self.image_stack.setMinimumSize(QtCore.QSize(200, 200))
        self.image_stack.setText("")
        self.image_stack.setPixmap(QtGui.QPixmap("dslr-camera.svg"))
        self.image_stack.setScaledContents(False)
        self.image_stack.setAlignment(QtCore.Qt.AlignCenter)
        self.image_stack.setObjectName("image_stack")
        AlsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AlsWindow)
        self.cDark.clicked['bool'].connect(self.fDark.setEnabled)
        self.cDark.clicked['bool'].connect(self.pbDark.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(AlsWindow)

    def retranslateUi(self, AlsWindow):
        _translate = QtCore.QCoreApplication.translate
        AlsWindow.setWindowTitle(_translate("AlsWindow", "MainWindow"))
        self.pbPlay.setText(_translate("AlsWindow", "Play"))
        self.pbPause.setText(_translate("AlsWindow", "Pause"))
        self.pbStop.setText(_translate("AlsWindow", "Stop"))
        self.cDark.setText(_translate("AlsWindow", "usedark"))
        self.pbWork.setText(_translate("AlsWindow", "Fwork"))
        self.pbScan.setText(_translate("AlsWindow", "Fscan"))
        self.pbDark.setText(_translate("AlsWindow", "Fichier Dark"))
        self.lCounter.setText(_translate("AlsWindow", "0"))
        self.cAlign.setText(_translate("AlsWindow", "align"))
        self.comboBox.setItemText(0, _translate("AlsWindow", "sum"))
        self.comboBox.setItemText(1, _translate("AlsWindow", "mean"))
        self.cEnablewww.setText(_translate("AlsWindow", "enablewww"))
        self.cKeepframes.setText(_translate("AlsWindow", "keepframes"))
        self.pbSave.setText(_translate("AlsWindow", "saveframe"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AlsWindow = QtWidgets.QMainWindow()
    ui = Ui_AlsWindow()
    ui.setupUi(AlsWindow)
    AlsWindow.show()
    sys.exit(app.exec_())
