# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alsui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stack_window(object):
    def setupUi(self, stack_window):
        stack_window.setObjectName("stack_window")
        stack_window.resize(872, 792)
        self.centralwidget = QtWidgets.QWidget(stack_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupScan = QtWidgets.QGroupBox(self.centralwidget)
        self.groupScan.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupScan.setObjectName("groupScan")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupScan)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tFolder = QtWidgets.QLineEdit(self.groupScan)
        self.tFolder.setEnabled(False)
        self.tFolder.setObjectName("tFolder")
        self.gridLayout_2.addWidget(self.tFolder, 0, 1, 1, 1)
        self.bBrowseFolder = QtWidgets.QPushButton(self.groupScan)
        self.bBrowseFolder.setObjectName("bBrowseFolder")
        self.gridLayout_2.addWidget(self.bBrowseFolder, 0, 2, 1, 1)
        self.cbAlign = QtWidgets.QCheckBox(self.groupScan)
        self.cbAlign.setObjectName("cbAlign")
        self.gridLayout_2.addWidget(self.cbAlign, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupScan)
        self.groupDark = QtWidgets.QGroupBox(self.centralwidget)
        self.groupDark.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupDark.setObjectName("groupDark")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupDark)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tDark = QtWidgets.QLineEdit(self.groupDark)
        self.tDark.setEnabled(False)
        self.tDark.setObjectName("tDark")
        self.gridLayout_3.addWidget(self.tDark, 1, 0, 1, 1)
        self.bBrowseDark = QtWidgets.QPushButton(self.groupDark)
        self.bBrowseDark.setEnabled(False)
        self.bBrowseDark.setObjectName("bBrowseDark")
        self.gridLayout_3.addWidget(self.bBrowseDark, 1, 1, 1, 1)
        self.cbDark = QtWidgets.QCheckBox(self.groupDark)
        self.cbDark.setObjectName("cbDark")
        self.gridLayout_3.addWidget(self.cbDark, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupDark)
        self.groupActions = QtWidgets.QGroupBox(self.centralwidget)
        self.groupActions.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupActions.setObjectName("groupActions")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupActions)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbPlay = QtWidgets.QPushButton(self.groupActions)
        self.pbPlay.setObjectName("pbPlay")
        self.horizontalLayout.addWidget(self.pbPlay)
        self.pbStop = QtWidgets.QPushButton(self.groupActions)
        self.pbStop.setEnabled(False)
        self.pbStop.setObjectName("pbStop")
        self.horizontalLayout.addWidget(self.pbStop)
        self.pbReset = QtWidgets.QPushButton(self.groupActions)
        self.pbReset.setObjectName("pbReset")
        self.horizontalLayout.addWidget(self.pbReset)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupActions)
        self.groupWrk = QtWidgets.QGroupBox(self.centralwidget)
        self.groupWrk.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupWrk.setObjectName("groupWrk")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupWrk)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 29, 821, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tWork = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tWork.setEnabled(False)
        self.tWork.setObjectName("tWork")
        self.gridLayout.addWidget(self.tWork, 0, 0, 1, 1)
        self.bBrowseWork = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bBrowseWork.setObjectName("bBrowseWork")
        self.gridLayout.addWidget(self.bBrowseWork, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupWrk)
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setMaximumSize(QtCore.QSize(16777215, 80))
        self.log.setObjectName("log")
        self.verticalLayout.addWidget(self.log)
        self.image_scene = QtWidgets.QGraphicsView(self.centralwidget)
        self.image_scene.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_scene.sizePolicy().hasHeightForWidth())
        self.image_scene.setSizePolicy(sizePolicy)
        self.image_scene.setMinimumSize(QtCore.QSize(320, 200))
        self.image_scene.setMaximumSize(QtCore.QSize(80, 80))
        self.image_scene.setObjectName("image_scene")
        self.verticalLayout.addWidget(self.image_scene)
        stack_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(stack_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 872, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        stack_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(stack_window)
        self.statusbar.setObjectName("statusbar")
        stack_window.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(stack_window)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(stack_window)
        self.actionQuit.triggered.connect(stack_window.close)
        self.cbDark.clicked['bool'].connect(self.tDark.setEnabled)
        self.cbDark.clicked['bool'].connect(self.bBrowseDark.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(stack_window)

    def retranslateUi(self, stack_window):
        _translate = QtCore.QCoreApplication.translate
        stack_window.setWindowTitle(_translate("stack_window", "MainWindow"))
        self.groupScan.setTitle(_translate("stack_window", "Répertoire à scanner"))
        self.tFolder.setText(_translate("stack_window", "~/als/scan"))
        self.bBrowseFolder.setText(_translate("stack_window", "..."))
        self.cbAlign.setText(_translate("stack_window", "Alignement"))
        self.groupDark.setTitle(_translate("stack_window", "Dark"))
        self.tDark.setText(_translate("stack_window", "~/als/dark.fits"))
        self.bBrowseDark.setText(_translate("stack_window", "..."))
        self.cbDark.setText(_translate("stack_window", "Utiliser un dark :"))
        self.groupActions.setTitle(_translate("stack_window", "Actions"))
        self.pbPlay.setText(_translate("stack_window", "Play"))
        self.pbStop.setText(_translate("stack_window", "Stop"))
        self.pbReset.setText(_translate("stack_window", "Reset"))
        self.groupWrk.setTitle(_translate("stack_window", "Dossier de travail"))
        self.tWork.setText(_translate("stack_window", "~/als/wrk"))
        self.bBrowseWork.setText(_translate("stack_window", "..."))
        self.menuFile.setTitle(_translate("stack_window", "Fi&le"))
        self.actionQuit.setText(_translate("stack_window", "&Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    stack_window = QtWidgets.QMainWindow()
    ui = Ui_stack_window()
    ui.setupUi(stack_window)
    stack_window.show()
    sys.exit(app.exec_())

