# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sdurand/git/perso/als/alsui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_stack_window(object):
    def setupUi(self, stack_window):
        stack_window.setObjectName("stack_window")
        stack_window.resize(818, 886)
        self.centralwidget = QtWidgets.QWidget(stack_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.tWork = QtWidgets.QLineEdit(self.centralwidget)
        self.tWork.setEnabled(False)
        self.tWork.setObjectName("tWork")
        self.gridLayout.addWidget(self.tWork, 3, 1, 1, 1)
        self.bBrowseFolder = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bBrowseFolder.sizePolicy().hasHeightForWidth())
        self.bBrowseFolder.setSizePolicy(sizePolicy)
        self.bBrowseFolder.setMinimumSize(QtCore.QSize(20, 0))
        self.bBrowseFolder.setMaximumSize(QtCore.QSize(80, 16777215))
        self.bBrowseFolder.setObjectName("bBrowseFolder")
        self.gridLayout.addWidget(self.bBrowseFolder, 0, 0, 1, 1)
        self.cbDark = QtWidgets.QCheckBox(self.centralwidget)
        self.cbDark.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbDark.setObjectName("cbDark")
        self.gridLayout.addWidget(self.cbDark, 1, 2, 1, 1)
        self.pbPlay = QtWidgets.QPushButton(self.centralwidget)
        self.pbPlay.setObjectName("pbPlay")
        self.gridLayout.addWidget(self.pbPlay, 0, 3, 1, 1)
        self.pbReset = QtWidgets.QPushButton(self.centralwidget)
        self.pbReset.setObjectName("pbReset")
        self.gridLayout.addWidget(self.pbReset, 3, 3, 1, 1)
        self.tDark = QtWidgets.QLineEdit(self.centralwidget)
        self.tDark.setEnabled(False)
        self.tDark.setObjectName("tDark")
        self.gridLayout.addWidget(self.tDark, 1, 1, 1, 1)
        self.tFolder = QtWidgets.QLineEdit(self.centralwidget)
        self.tFolder.setEnabled(False)
        self.tFolder.setObjectName("tFolder")
        self.gridLayout.addWidget(self.tFolder, 0, 1, 1, 1)
        self.bBrowseDark = QtWidgets.QPushButton(self.centralwidget)
        self.bBrowseDark.setEnabled(False)
        self.bBrowseDark.setMaximumSize(QtCore.QSize(80, 16777215))
        self.bBrowseDark.setObjectName("bBrowseDark")
        self.gridLayout.addWidget(self.bBrowseDark, 1, 0, 1, 1)
        self.bBrowseWork = QtWidgets.QPushButton(self.centralwidget)
        self.bBrowseWork.setMaximumSize(QtCore.QSize(80, 16777215))
        self.bBrowseWork.setObjectName("bBrowseWork")
        self.gridLayout.addWidget(self.bBrowseWork, 3, 0, 1, 1)
        self.pbStop = QtWidgets.QPushButton(self.centralwidget)
        self.pbStop.setEnabled(False)
        self.pbStop.setObjectName("pbStop")
        self.gridLayout.addWidget(self.pbStop, 1, 3, 1, 1)
        self.cbAlign = QtWidgets.QCheckBox(self.centralwidget)
        self.cbAlign.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbAlign.setChecked(True)
        self.cbAlign.setObjectName("cbAlign")
        self.gridLayout.addWidget(self.cbAlign, 0, 2, 1, 1)
        self.cmMode = QtWidgets.QComboBox(self.centralwidget)
        self.cmMode.setObjectName("cmMode")
        self.cmMode.addItem("")
        self.cmMode.addItem("")
        self.gridLayout.addWidget(self.cmMode, 3, 2, 1, 1)
        self.pbSave = QtWidgets.QPushButton(self.centralwidget)
        self.pbSave.setObjectName("pbSave")
        self.gridLayout.addWidget(self.pbSave, 4, 3, 1, 1)
        self.cnt = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cnt.setFont(font)
        self.cnt.setAlignment(QtCore.Qt.AlignCenter)
        self.cnt.setObjectName("cnt")
        self.gridLayout.addWidget(self.cnt, 4, 1, 1, 1)
        self.cbKeep = QtWidgets.QCheckBox(self.centralwidget)
        self.cbKeep.setObjectName("cbKeep")
        self.gridLayout.addWidget(self.cbKeep, 4, 2, 1, 1)
        self.cbWww = QtWidgets.QCheckBox(self.centralwidget)
        self.cbWww.setObjectName("cbWww")
        self.gridLayout.addWidget(self.cbWww, 4, 0, 1, 1)
        self.gridLayout.setColumnMinimumWidth(1, 50)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setMinimumSize(QtCore.QSize(300, 120))
        self.log.setMaximumSize(QtCore.QSize(16777215, 500))
        self.log.setObjectName("log")
        self.horizontalLayout.addWidget(self.log)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.image_stack = QtWidgets.QLabel(self.centralwidget)
        self.image_stack.setMinimumSize(QtCore.QSize(800, 600))
        self.image_stack.setText("")
        self.image_stack.setPixmap(QtGui.QPixmap("dslr-camera.svg"))
        self.image_stack.setAlignment(QtCore.Qt.AlignCenter)
        self.image_stack.setObjectName("image_stack")
        self.verticalLayout.addWidget(self.image_stack)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.contrast_silder = QtWidgets.QSlider(self.centralwidget)
        self.contrast_silder.setMinimum(1)
        self.contrast_silder.setMaximum(100)
        self.contrast_silder.setOrientation(QtCore.Qt.Horizontal)
        self.contrast_silder.setObjectName("contrast_silder")
        self.horizontalLayout_3.addWidget(self.contrast_silder)
        self.contrast = QtWidgets.QLabel(self.centralwidget)
        self.contrast.setObjectName("contrast")
        self.horizontalLayout_3.addWidget(self.contrast)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.luminosity_slider = QtWidgets.QSlider(self.centralwidget)
        self.luminosity_slider.setMaximum(32000)
        self.luminosity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.luminosity_slider.setObjectName("luminosity_slider")
        self.horizontalLayout_4.addWidget(self.luminosity_slider)
        self.luminosity = QtWidgets.QLabel(self.centralwidget)
        self.luminosity.setObjectName("luminosity")
        self.horizontalLayout_4.addWidget(self.luminosity)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.black_slider = QtWidgets.QSlider(self.centralwidget)
        self.black_slider.setMaximum(65535)
        self.black_slider.setOrientation(QtCore.Qt.Horizontal)
        self.black_slider.setObjectName("black_slider")
        self.horizontalLayout_5.addWidget(self.black_slider)
        self.black = QtWidgets.QLabel(self.centralwidget)
        self.black.setObjectName("black")
        self.horizontalLayout_5.addWidget(self.black)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.white_slider = QtWidgets.QSlider(self.centralwidget)
        self.white_slider.setMaximum(65535)
        self.white_slider.setSliderPosition(65535)
        self.white_slider.setOrientation(QtCore.Qt.Horizontal)
        self.white_slider.setObjectName("white_slider")
        self.horizontalLayout_6.addWidget(self.white_slider)
        self.white = QtWidgets.QLabel(self.centralwidget)
        self.white.setObjectName("white")
        self.horizontalLayout_6.addWidget(self.white)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pb_apply_value = QtWidgets.QPushButton(self.centralwidget)
        self.pb_apply_value.setObjectName("pb_apply_value")
        self.verticalLayout.addWidget(self.pb_apply_value)
        stack_window.setCentralWidget(self.centralwidget)
        self.actionQuit = QtWidgets.QAction(stack_window)
        self.actionQuit.setObjectName("actionQuit")

        self.retranslateUi(stack_window)
        self.actionQuit.triggered.connect(stack_window.close)
        self.cbDark.clicked['bool'].connect(self.tDark.setEnabled)
        self.cbDark.clicked['bool'].connect(self.bBrowseDark.setEnabled)
        self.cbAlign.clicked['bool'].connect(self.cmMode.setEnabled)
        self.contrast_silder.sliderMoved['int'].connect(self.contrast.setNum)
        self.luminosity_slider.sliderMoved['int'].connect(self.luminosity.setNum)
        self.black_slider.sliderMoved['int'].connect(self.black.setNum)
        self.white_slider.sliderMoved['int'].connect(self.white.setNum)
        QtCore.QMetaObject.connectSlotsByName(stack_window)

    def retranslateUi(self, stack_window):
        _translate = QtCore.QCoreApplication.translate
        stack_window.setWindowTitle(_translate("stack_window", "Astro Live Stacker"))
        self.tWork.setText(_translate("stack_window", "~/als/wrk"))
        self.bBrowseFolder.setText(_translate("stack_window", "Rep. scan"))
        self.cbDark.setText(_translate("stack_window", "Utiliser un dark"))
        self.pbPlay.setText(_translate("stack_window", "Play"))
        self.pbReset.setText(_translate("stack_window", "Reset"))
        self.tDark.setText(_translate("stack_window", "~/als/dark.fits"))
        self.tFolder.setText(_translate("stack_window", "~/als/scan"))
        self.bBrowseDark.setText(_translate("stack_window", "Fic. dark"))
        self.bBrowseWork.setText(_translate("stack_window", "Rep. wrk"))
        self.pbStop.setText(_translate("stack_window", "Stop"))
        self.cbAlign.setText(_translate("stack_window", "Aligner"))
        self.cmMode.setItemText(0, _translate("stack_window", "Sum"))
        self.cmMode.setItemText(1, _translate("stack_window", "Mean"))
        self.pbSave.setText(_translate("stack_window", "Save"))
        self.cnt.setText(_translate("stack_window", "0"))
        self.cbKeep.setText(_translate("stack_window", "Conserver les images"))
        self.cbWww.setText(_translate("stack_window", "www"))
        self.label_2.setText(_translate("stack_window", "Contrast :"))
        self.contrast.setText(_translate("stack_window", "1"))
        self.label_3.setText(_translate("stack_window", "Luminosity :"))
        self.luminosity.setText(_translate("stack_window", "0"))
        self.label_5.setText(_translate("stack_window", "Black min value :"))
        self.black.setText(_translate("stack_window", "0"))
        self.label_6.setText(_translate("stack_window", "White max value :"))
        self.white.setText(_translate("stack_window", "65535"))
        self.pb_apply_value.setText(_translate("stack_window", "Apply"))
        self.actionQuit.setText(_translate("stack_window", "&Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    stack_window = QtWidgets.QMainWindow()
    ui = Ui_stack_window()
    ui.setupUi(stack_window)
    stack_window.show()
    sys.exit(app.exec_())

